name: linux

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build-cmake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: ["gcc", "clang"]
        shared: [YES, NO]
        build_type: [Release]

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: dependencies
        run: |
          sudo apt -y update
          sudo apt -y install ninja-build libsdl2-dev

      - name: Check that versioning is consistent
        run: ./test-versioning.sh

      - name: Configure CMake
        env:
          CC: ${{matrix.compiler}}
        run: |
          cmake -S . -B build -D CMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -G Ninja -D BUILD_SHARED_LIBS=${{matrix.shared}}

      - name: Build CMake
        run: ninja -C build
  build-make:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: ["gcc", "clang"]

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: dependencies
        run: |
          sudo apt -y update
          sudo apt -y install \
            autoconf \
            libtool \
            libsdl2-dev \
            ${NULL+}

      - name: Configure make
        env:
          CC: ${{matrix.compiler}}
        run: |
          ./autogen.sh
          ./configure

      - name: Build make
        run: make -j2

      - name: Distcheck
        run: |
          set -eu
          parallel="$(getconf _NPROCESSORS_ONLN)"
          make -j"${parallel}" dist V=1
          # Similar to Automake `make distcheck`: check that the tarball
          # release is sufficient to do a new build
          mkdir distcheck
          tar -C distcheck -zxf SDL2_mixer-*.tar.gz
          ( cd distcheck/SDL2_mixer-* && ./configure )
          make -C distcheck/SDL2_mixer-*
